// Translate this into a JSON object with 3-letter as property name, 2 letter as value.
// Switch display to javascript src management.

var languagecodes = {
aar:	"Afar",
aav:	"Austro-Asiatic languages",
abk:	"Abkhazian",
ace:	"Achinese",
ach:	"Acoli",
ada:	"Adangme",
ady:	"Adyghe",
afa:	"Afro-Asiatic languages",
afh:	"Afrihili",
afr:	"Afrikaans",
ain:	"Ainu (Japan)",
aka:	"Akan",
akk:	"Akkadian",
alb:	"Albanian",
sqi:	"Albanian",
ale:	"Aleut",
alg:	"Algonquian languages",
alt:	"Southern Altai",
alv:	"Atlantic-Congo languages",
amh:	"Amharic",
ang:	"Old English (ca. 450-1100)",
anp:	"Angika",
apa:	"Apache languages",
aqa:	"Alacalufan languages",
aql:	"Algic languages",
ara:	"Arabic",
arc:	"Official Aramaic (700-300 BCE)",
arg:	"Aragonese",
arm:	"Armenian",
hye:	"Armenian",
arn:	"Mapudungun",
arp:	"Arapaho",
art:	"Artificial languages",
arw:	"Arawak",
asm:	"Assamese",
ast:	"Asturian",
ath:	"Athapascan languages",
auf:	"Arauan languages",
aus:	"Australian languages",
ava:	"Avaric",
ave:	"Avestan",
awa:	"Awadhi",
awd:	"Arawakan languages",
aym:	"Aymara",
azc:	"Uto-Aztecan languages",
aze:	"Azerbaijani",
bad:	"Banda languages",
bai:	"Bamileke languages",
bak:	"Bashkir",
bal:	"Baluchi",
bam:	"Bambara",
ban:	"Balinese",
baq:	"Basque",
eus:	"Basque",
bas:	"Basa (Cameroon)",
bat:	"Baltic languages",
bej:	"Beja",
bel:	"Belarusian",
bem:	"Bemba (Zambia)",
ben:	"Bengali",
ber:	"Berber languages",
bho:	"Bhojpuri",
bih:	"Bihari languages",
bik:	"Bikol",
bin:	"Bini",
bis:	"Bislama",
bla:	"Siksika",
bnt:	"Bantu languages",
bod:	"Tibetan",
tib:	"Tibetan",
bos:	"Bosnian",
bra:	"Braj",
bre:	"Breton",
btk:	"Batak languages",
bua:	"Buriat",
bug:	"Buginese",
bul:	"Bulgarian",
bur:	"Burmese",
mya:	"Burmese",
byn:	"Bilin",
cad:	"Caddo",
cai:	"Central American Indian languages",
car:	"Galibi Carib",
cat:	"Catalan",
cau:	"Caucasian languages",
cba:	"Chibchan languages",
ccn:	"North Caucasian languages",
ccs:	"South Caucasian languages",
cdc:	"Chadic languages",
cdd:	"Caddoan languages",
ceb:	"Cebuano",
cel:	"Celtic languages",
ces:	"Czech",
cze:	"Czech",
cha:	"Chamorro",
chb:	"Chibcha",
che:	"Chechen",
chg:	"Chagatai",
chi:	"Chinese",
zho:	"Chinese",
chk:	"Chuukese",
chm:	"Mari (Russia)",
chn:	"Chinook jargon",
cho:	"Choctaw",
chp:	"Chipewyan",
chr:	"Cherokee",
chu:	"Church Slavic",
chv:	"Chuvash",
chy:	"Cheyenne",
cmc:	"Chamic languages",
cop:	"Coptic",
cor:	"Cornish",
cos:	"Corsican",
cpe:	"English based Creoles and pidgins",
cpf:	"French-Based Creoles and pidgins",
cpp:	"Portuguese-Based Creoles and pidgins",
cre:	"Cree",
crh:	"Crimean Tatar",
crp:	"Creoles and pidgins",
csb:	"Kashubian",
csu:	"Central Sudanic languages",
cus:	"Cushitic languages",
cym:	"Welsh",
wel:	"Welsh",
cze:	"Czech",
ces:	"Czech",
dak:	"Dakota",
dan:	"Danish",
dar:	"Dargwa",
day:	"Land Dayak languages",
del:	"Delaware",
den:	"Slave (Athapascan)",
deu:	"German",
ger:	"German",
dgr:	"Dogrib",
din:	"Dinka",
div:	"Dhivehi",
dmn:	"Mande languages",
doi:	"Dogri (macrolanguage)",
dra:	"Dravidian languages",
dsb:	"Lower Sorbian",
dua:	"Duala",
dum:	"Middle Dutch (ca. 1050-1350)",
dut:	"Dutch",
nld:	"Dutch",
dyu:	"Dyula",
dzo:	"Dzongkha",
efi:	"Efik",
egx:	"Egyptian languages",
egy:	"Egyptian (Ancient)",
eka:	"Ekajuk",
elx:	"Elamite",
eng:	"English",
enm:	"Middle English (1100-1500)",
epo:	"Esperanto",
est:	"Estonian",
esx:	"Eskimo-Aleut languages",
euq:	"Basque (family)",
eus:	"Basque",
baq:	"Basque",
ewe:	"Ewe",
ewo:	"Ewondo",
fan:	"Fang (Equatorial Guinea)",
fao:	"Faroese",
fas:	"Persian",
per:	"Persian",
fat:	"Fanti",
fij:	"Fijian",
fil:	"Filipino",
fin:	"Finnish",
fiu:	"Finno-Ugrian languages",
fon:	"Fon",
fox:	"Formosan languages",
fra:	"French",
fre:	"French",
frm:	"Middle French (ca. 1400-1600)",
fro:	"Old French (842-ca. 1400)",
frr:	"Northern Frisian",
frs:	"Eastern Frisian",
fry:	"Western Frisian",
ful:	"Fulah",
fur:	"Friulian",
gaa:	"Ga",
gay:	"Gayo",
gba:	"Gbaya (Central African Republic)",
gem:	"Germanic languages",
geo:	"Georgian",
kat:	"Georgian",
ger:	"German",
deu:	"German",
gez:	"Geez",
gil:	"Gilbertese",
gla:	"Scottish Gaelic",
gle:	"Irish",
glg:	"Galician",
glv:	"Manx",
gme:	"East Germanic languages",
gmh:	"Middle High German (ca. 1050-1500)",
gmq:	"North Germanic languages",
gmw:	"West Germanic languages",
goh:	"Old High German (ca. 750-1050)",
gon:	"Gondi",
gor:	"Gorontalo",
got:	"Gothic",
grb:	"Grebo",
grc:	"Ancient Greek (to 1453)",
gre:	"Modern Greek (1453-)",
ell:	"Modern Greek (1453-)",
grk:	"Greek languages",
grn:	"Guarani",
gsw:	"Swiss German",
guj:	"Gujarati",
gwi:	"Gwichʼin",
hai:	"Haida",
hat:	"Haitian",
hau:	"Hausa",
haw:	"Hawaiian",
heb:	"Hebrew",
her:	"Herero",
hil:	"Hiligaynon",
him:	"Himachali languages",
hin:	"Hindi",
hit:	"Hittite",
hmn:	"Hmong",
hmo:	"Hiri Motu",
hmx:	"Hmong-Mien languages",
hok:	"Hokan languages",
hrv:	"Croatian",
hsb:	"Upper Sorbian",
hun:	"Hungarian",
hup:	"Hupa",
hye:	"Armenian",
arm:	"Armenian",
hyx:	"Armenian (family)",
iba:	"Iban",
ibo:	"Igbo",
ice:	"Icelandic",
isl:	"Icelandic",
ido:	"Ido",
iii:	"Sichuan Yi",
iir:	"Indo-Iranian languages",
ijo:	"Ijo languages",
iku:	"Inuktitut",
ile:	"Interlingue",
ilo:	"Iloko",
ina:	"Interlingua (International Auxiliary Language Association)",
inc:	"Indic languages",
ind:	"Indonesian",
ine:	"Indo-European languages",
inh:	"Ingush",
ipk:	"Inupiaq",
ira:	"Iranian languages",
iro:	"Iroquoian languages",
isl:	"Icelandic",
ice:	"Icelandic",
ita:	"Italian",
itc:	"Italic languages",
jav:	"Javanese",
jbo:	"Lojban",
jpn:	"Japanese",
jpr:	"Judeo-Persian",
jpx:	"Japanese (family)",
jrb:	"Judeo-Arabic",
kaa:	"Kara-Kalpak",
kab:	"Kabyle",
kac:	"Kachin",
kal:	"Kalaallisut",
kam:	"Kamba (Kenya)",
kan:	"Kannada",
kar:	"Karen languages",
kas:	"Kashmiri",
kat:	"Georgian",
geo:	"Georgian",
kau:	"Kanuri",
kaw:	"Kawi",
kaz:	"Kazakh",
kbd:	"Kabardian",
kdo:	"Kordofanian languages",
kha:	"Khasi",
khi:	"Khoisan languages",
khm:	"Central Khmer",
kho:	"Khotanese",
kik:	"Kikuyu",
kin:	"Kinyarwanda",
kir:	"Kirghiz",
kmb:	"Kimbundu",
kok:	"Konkani (macrolanguage)",
kom:	"Komi",
kon:	"Kongo",
kor:	"Korean",
kos:	"Kosraean",
kpe:	"Kpelle",
krc:	"Karachay-Balkar",
krl:	"Karelian",
kro:	"Kru languages",
kru:	"Kurukh",
kua:	"Kuanyama",
kum:	"Kumyk",
kur:	"Kurdish",
kut:	"Kutenai",
lad:	"Ladino",
lah:	"Lahnda",
lam:	"Lamba",
lao:	"Lao",
lat:	"Latin",
lav:	"Latvian",
lez:	"Lezghian",
lim:	"Limburgan",
lin:	"Lingala",
lit:	"Lithuanian",
lol:	"Mongo",
loz:	"Lozi",
ltz:	"Luxembourgish",
lua:	"Luba-Lulua",
lub:	"Luba-Katanga",
lug:	"Ganda",
lui:	"Luiseno",
lun:	"Lunda",
luo:	"Luo (Kenya and Tanzania)",
lus:	"Lushai",
mac:	"Macedonian",
mkd:	"Macedonian",
mad:	"Madurese",
mag:	"Magahi",
mah:	"Marshallese",
mai:	"Maithili",
mak:	"Makasar",
mal:	"Malayalam",
man:	"Mandingo",
mao:	"Maori",
mri:	"Maori",
map:	"Austronesian languages",
mar:	"Marathi",
mas:	"Masai",
may:	"Malay (macrolanguage)",
msa:	"Malay (macrolanguage)",
mdf:	"Moksha",
mdr:	"Mandar",
men:	"Mende (Sierra Leone)",
mga:	"Middle Irish (900-1200)",
mic:	"Mi'kmaq",
min:	"Minangkabau",
mis:	"Uncoded languages",
mkd:	"Macedonian",
mac:	"Macedonian",
mkh:	"Mon-Khmer languages",
mlg:	"Malagasy",
mlt:	"Maltese",
mnc:	"Manchu",
mni:	"Manipuri",
mno:	"Manobo languages",
moh:	"Mohawk",
mon:	"Mongolian",
mos:	"Mossi",
mri:	"Maori",
mao:	"Maori",
msa:	"Malay (macrolanguage)",
may:	"Malay (macrolanguage)",
mul:	"Multiple languages",
mun:	"Munda languages",
mus:	"Creek",
mwl:	"Mirandese",
mwr:	"Marwari",
mya:	"Burmese",
bur:	"Burmese",
myn:	"Mayan languages",
myv:	"Erzya",
nah:	"Nahuatl languages",
nai:	"North American Indian",
nap:	"Neapolitan",
nau:	"Nauru",
nav:	"Navajo",
nbl:	"South Ndebele",
nde:	"North Ndebele",
ndo:	"Ndonga",
nds:	"Low German",
nep:	"Nepali (macrolanguage)",
new:	"Nepal Bhasa",
ngf:	"Trans-New Guinea languages",
nia:	"Nias",
nic:	"Niger-Kordofanian languages",
niu:	"Niuean",
nld:	"Dutch",
dut:	"Dutch",
nno:	"Norwegian Nynorsk",
nob:	"Norwegian Bokmål",
nog:	"Nogai",
non:	"Old Norse",
nor:	"Norwegian",
nqo:	"N'Ko",
nso:	"Pedi",
nub:	"Nubian languages",
nwc:	"Classical Newari",
nya:	"Nyanja",
nym:	"Nyamwezi",
nyn:	"Nyankole",
nyo:	"Nyoro",
nzi:	"Nzima",
oci:	"Occitan (post 1500)",
oji:	"Ojibwa",
omq:	"Oto-Manguean languages",
omv:	"Omotic languages",
ori:	"Odiya (macrolanguage)",
orm:	"Oromo",
osa:	"Osage",
oss:	"Ossetian",
ota:	"Ottoman Turkish (1500-1928)",
oto:	"Otomian languages",
paa:	"Papuan languages",
pag:	"Pangasinan",
pal:	"Pahlavi",
pam:	"Pampanga",
pan:	"Panjabi",
pap:	"Papiamento",
pau:	"Palauan",
peo:	"Old Persian (ca. 600-400 B.C.)",
per:	"Persian",
fas: 	"Persian",
phi:	"Philippine languages",
phn:	"Phoenician",
plf:	"Central Malayo-Polynesian languages",
pli:	"Pali",
pol:	"Polish",
pon:	"Pohnpeian",
por:	"Portuguese",
poz:	"Malayo-Polynesian languages",
pqe:	"Eastern Malayo-Polynesian languages",
pqw:	"Western Malayo-Polynesian languages",
pra:	"Prakrit languages",
pro:	"Old Provençal (to 1500)",
pus:	"Pushto",
qaaqtz:	"Reserved for local use",
que:	"Quechua",
qwe:	"Quechuan (family)",
raj:	"Rajasthani",
rap:	"Rapanui",
rar:	"Rarotongan",
roa:	"Romance languages",
roh:	"Romansh",
rom:	"Romany",
ron:	"Romanian",
rum:    "Romanian",
run:	"Rundi",
rup:	"Macedo-Romanian",
rus:	"Russian",
sad:	"Sandawe",
sag:	"Sango",
sah:	"Yakut",
sai:	"South American Indian languages",
sal:	"Salishan languages",
sam:	"Samaritan Aramaic",
san:	"Sanskrit",
sas:	"Sasak",
sat:	"Santali",
scn:	"Sicilian",
sco:	"Scots",
sdv:	"Eastern Sudanic languages",
sel:	"Selkup",
sem:	"Semitic languages",
sga:	"Old Irish (to 900)",
sgn:	"Sign languages",
shn:	"Shan",
sid:	"Sidamo",
sin:	"Sinhala",
sio:	"Siouan languages",
sit:	"Sino-Tibetan languages",
sla:	"Slavic languages",
slk:	"Slovak",
slo:    "Slovak",
slv:	"Slovenian",
sma:	"Southern Sami",
sme:	"Northern Sami",
smi:	"Sami languages",
smj:	"Lule Sami",
smn:	"Inari Sami",
smo:	"Samoan",
sms:	"Skolt Sami",
sna:	"Shona",
snd:	"Sindhi",
snk:	"Soninke",
sog:	"Sogdian",
som:	"Somali",
son:	"Songhai languages",
sot:	"Southern Sotho",
spa:	"Spanish",
sqi:	"Albanian",
alb:    "Albanian",
sqi:	"Albanian languages",
srd:	"Sardinian",
srn:	"Sranan Tongo",
srp:	"Serbian",
srr:	"Serer",
ssa:	"Nilo-Saharan languages",
ssw:	"Swati",
suk:	"Sukuma",
sun:	"Sundanese",
sus:	"Susu",
sux:	"Sumerian",
swa:	"Swahili (macrolanguage)",
swe:	"Swedish",
syc:	"Classical Syriac",
syd:	"Samoyedic languages",
syr:	"Syriac",
tah:	"Tahitian",
tai:	"Tai languages",
tam:	"Tamil",
tat:	"Tatar",
tbq:	"Tibeto-Burman languages",
tel:	"Telugu",
tem:	"Timne",
ter:	"Tereno",
tet:	"Tetum",
tgk:	"Tajik",
tgl:	"Tagalog",
tha:	"Thai",
tib:    "Tibetan",
bod:	"Tibetan",
tig:	"Tigre",
tir:	"Tigrinya",
tiv:	"Tiv",
tkl:	"Tokelau",
tlh:	"Klingon",
tli:	"Tlingit",
tmh:	"Tamashek",
tog:	"Tonga (Nyasa)",
ton:	"Tonga (Tonga Islands)",
tpi:	"Tok Pisin",
trk:	"Turkic languages",
tsi:	"Tsimshian",
tsn:	"Tswana",
tso:	"Tsonga",
tuk:	"Turkmen",
tum:	"Tumbuka",
tup:	"Tupi languages",
tur:	"Turkish",
tut:	"Altaic languages",
tuw:	"Tungus languages",
tvl:	"Tuvalu",
twi:	"Twi",
tyv:	"Tuvinian",
udm:	"Udmurt",
uga:	"Ugaritic",
uig:	"Uighur",
ukr:	"Ukrainian",
umb:	"Umbundu",
und:	"Undetermined",
urd:	"Urdu",
urj:	"Uralic languages",
uzb:	"Uzbek",
vai:	"Vai",
ven:	"Venda",
vie:	"Vietnamese",
vol:	"Volapük",
vot:	"Votic",
wak:	"Wakashan languages",
wal:	"Wolaytta",
war:	"Waray (Philippines)",
was:	"Washo",
wel:	"Welsh",
cym:    "Welsh",
wen:	"Sorbian languages",
wln:	"Walloon",
wol:	"Wolof",
xal:	"Kalmyk",
xgn:	"Mongolian languages",
xho:	"Xhosa",
xnd:	"Na-Dene languages",
yao:	"Yao",
yap:	"Yapese",
yid:	"Yiddish",
yor:	"Yoruba",
ypk:	"Yupik languages",
zap:	"Zapotec",
zbl:	"Blissymbols",
zen:	"Zenaga",
zgh:	"Standard Moroccan Tamazight",
zha:	"Zhuang",
zho:	"Chinese",
chi:	"Chinese",
zhx:	"Chinese (family)",
zle:	"East Slavic languages",
zls:	"South Slavic languages",
zlw:	"West Slavic languages",
znd:	"Zande languages",
zul:	"Zulu",
zun:	"Zuni",
zxx:	"No linguistic content",
zza:	"Zaza"
};