######################################################################################################################
#	Plex WebTools helper unit for Plex2CSV module					
#
#	Author: dane22, a Plex Community member
#
######################################################################################################################

# Fields that contains a timestamp and should return a date
dateTimeFields = ['addedAt', 'updatedAt', 'lastViewedAt']

# Fields that contains a timestamp and should return a time
timeFields =['duration']

fields = {
				"Media ID" : {"field" : "@ratingKey", "ReqLevel" : 1, "id" : 1},
				"Title" : {"field" : "@title", "ReqLevel" : 1, "id" : 2},
				"Sort title" : {"field" : "@titleSort", "ReqLevel" : 1, "id" : 3},
				"Studio" : {"field" : "@studio", "ReqLevel" : 1, "id" : 4},
				"Content Rating" : {"field" : "@contentRating", "ReqLevel" : 1, "id" : 5},
				"Year" : {"field" : "@year", "ReqLevel" : 1, "id" : 6},
				"Rating" : {"field" : "@rating", "ReqLevel" : 1, "id" : 7},
				"Summary" : {"field" : "@summary", "ReqLevel" : 1, "id" : 8},
				"Genres" : {"field" : "Genre/@tag", "ReqLevel" : 1, "id" : 9},
				"View Count" : {"field" : "@viewCount", "ReqLevel" : 1, "id" : 10},
				"Last Viewed at" : {"field" : "@lastViewedAt", "ReqLevel" : 1, "id" : 11},
				"Tagline" : {"field" : "@tagline", "ReqLevel" : 1, "id" : 12},
				"Release Date" : {"field" : "@originallyAvailableAt", "ReqLevel" : 1, "id" : 13},
				"Writers" : {"field" : "Writer/@tag", "ReqLevel" : 1, "id" : 14},
				"Country" : {"field" : "Country/@tag", "ReqLevel" : 1, "id" : 15},
				"Duration" : {"field" : "@duration", "ReqLevel" : 1, "id" : 16},
				"Directors" : {"field" : "Director/@tag", "ReqLevel" : 1, "id" : 17},
				"Roles" : {"field" : "Role/@tag", "ReqLevel" : 1, "id" : 18},
				"IMDB Id" : {"field" : "@guid", "ReqLevel" : 1, "id" : 19},
				"Labels" : {"fields" : "Label/@tag", "ReqLevel" : 2, "id" : 20},
				"Locked Fields" : {"field" : "Field/@name", "ReqLevel" : 2, "id" : 21},
				"Extras" : {"field" : "Extras/@size", "ReqLevel" : 2, "id" : 22},
				"Collections" : {"field" : "Collection/@tag", "ReqLevel" : 2, "id" : 23},
				"Original Title" : {"field" : "@originalTitle", "ReqLevel" : 2, "id" : 24},
				"Added" : {"field": "@addedAt", "ReqLevel" : 2, "id" : 25},
				"Updated" : {"field" : "@updatedAt", "ReqLevel" : 2, "id" : 26},
				"Audio Languages" : {"field" : "Media/Part/Stream[@streamType=2]/@languageCode", "ReqLevel" : 2, "id" : 27},
				"Audio Title" : {"field" : "Media/Part/Stream[@streamType=2]/@title", "ReqLevel" : 2, "id" : 28},
				"Subtitle Languages" : {"field" : "Media/Part/Stream[@streamType=3]/@languageCode", "ReqLevel" : 2, "id" : 29},
				"Subtitle Title" : {"field" : "Media/Part/Stream[@streamType=3]/@title", "ReqLevel" : 2, "id" : 30},
				"Subtitle Codec" : {"field" : "Media/Part/Stream[@streamType=3]/@codec", "ReqLevel" : 2, "id" : 31},
				"Accessible" : {"field" : "Media/Part/@accessible", "ReqLevel" : 2, "id" : 32},
				"Exists" : {"field" : "Media/Part/@exists", "ReqLevel" : 2, "id" : 33},
				"Video Resolution" : {"field" : "Media/@videoResolution", "ReqLevel" : 2, "id" : 34},
				"Bitrate" : {"field" : "Media/@bitrate", "ReqLevel" : 2, "id" : 35},
				"Width" : {"field" : "Media/@width", "ReqLevel" : 2, "id" : 36},
				"Height" : {"field" : "Media/@height", "ReqLevel" : 2, "id" : 37},
				"Aspect Ratio" : {"field" : "Media/@aspectRatio", "ReqLevel" : 2, "id" : 38},
				"Audio Channels" : {"field" : "Media/@audioChannels", "ReqLevel" : 2, "id" : 39},
				"Audio Codec" : {"field" : "Media/@audioCodec", "ReqLevel" : 2, "id" : 40},
				"Video Codec" : {"field" : "Media/@videoCodec", "ReqLevel" : 2, "id" : 41},
				"Container" : {"field" : "Media/@container", "ReqLevel" : 2, "id" : 42},
				"Video FrameRate" : {"field" : "Media/@videoFrameRate", "ReqLevel" : 2, "id" : 43},
				"Part File" : {"field" : "Media/Part/@file", "ReqLevel" : 2, "id" : 44},
				"Part Size" : {"field" : "Media/Part/@size", "ReqLevel" : 2, "id" : 45},
				"Part Indexed" : {"field" : "Media/Part/@indexes", "ReqLevel" : 2, "id" : 46},
				"Part Duration" : {"field" : "Media/Part/@duration", "ReqLevel" : 2, "id" : 47},
				"Part Container" : {"field" : "Media/Part/@container", "ReqLevel" : 2, "id" : 48},
				"Part Optimized for Streaming" : {"field" : "Media/Part/@optimizedForStreaming", "ReqLevel" : 2, "id" : 49},
				"Video Stream Title" : {"field" : "Media/Part/Stream[@streamType=1]/@title", "ReqLevel" : 2, "id" : 50},
				"Video Stream Default" : {"field" : "Media/Part/Stream[@streamType=1]/@default", "ReqLevel" : 2, "id" : 51},
				"Video Stream Index" : {"field" : "Media/Part/Stream[@streamType=1]/@index", "ReqLevel" : 2, "id" : 52},
				"Video Stream Pixel Format" : {"field" : "Media/Part/Stream[@streamType=1]/@pixelFormat", "ReqLevel" : 2, "id" : 53},
				"Video Stream Profile" : {"field" : "Media/Part/Stream[@streamType=1]/@profile", "ReqLevel" : 2, "id" : 54},
				"Video Stream Ref Frames" : {"field" : "Media/Part/Stream[@streamType=1]/@refFrames", "ReqLevel" : 2, "id" : 55},
				"Video Stream Scan Type" : {"field" : "Media/Part/Stream[@streamType=1]/@scanType", "ReqLevel" : 2, "id" : 56},
				"Video Stream Stream Identifier" : {"field" : "Media/Part/Stream[@streamType=1]/@streamIdentifier", "ReqLevel" : 2, "id" : 57},
				"Video Stream Width" : {"field" : "Media/Part/Stream[@streamType=1]/@width", "ReqLevel" : 2, "id" : 58},
				"Video Stream Pixel Aspect Ratio" : {"field" : "Media/Part/Stream[@streamType=1]/@pixelAspectRatio", "ReqLevel" : 2, "id" : 59},
				"Video Stream Height" : {"field" : "Media/Part/Stream[@streamType=1]/@height", "ReqLevel" : 2, "id" : 60},
				"Video Stream Has Scaling Matrix" : {"field" : "Media/Part/Stream[@streamType=1]/@hasScalingMatrix", "ReqLevel" : 2, "id" : 61},
				"Video Stream Frame Rate Mode" : {"field" : "Media/Part/Stream[@streamType=1]/@frameRateMode", "ReqLevel" : 2, "id" : 62},
				"Video Stream Frame Rate" : {"field" : "Media/Part/Stream[@streamType=1]/@frameRate", "ReqLevel" : 2, "id" : 63},
				"Video Stream Codec" : {"field" : "Media/Part/Stream[@streamType=1]/@codec", "ReqLevel" : 2, "id" : 64},
				"Video Stream Codec ID" : {"field" : "Media/Part/Stream[@streamType=1]/@codecID", "ReqLevel" : 2, "id" : 65},
				"Video Stream Chroma Sub Sampling" : {"field" : "Media/Part/Stream[@streamType=1]/@chromaSubsampling", "ReqLevel" : 2, "id" : 66},
				"Video Stream Cabac" : {"field" : "Media/Part/Stream[@streamType=1]/@cabac", "ReqLevel" : 2, "id" : 67},
				"Video Stream Anamorphic" : {"field" : "Media/Part/Stream[@streamType=1]/@anamorphic", "ReqLevel" : 2, "id" : 68},
				"Video Stream Language Code" : {"field" : "Media/Part/Stream[@streamType=1]/@languageCode", "ReqLevel" : 2, "id" : 69},
				"Video Stream Language" : {"field" : "Media/Part/Stream[@streamType=1]/@language", "ReqLevel" : 2, "id" : 70},
				"Video Stream Bitrate" : {"field" : "Media/Part/Stream[@streamType=1]/@bitrate", "ReqLevel" : 2, "id" : 71},
				"Video Stream Bit Depth" : {"field" : "Media/Part/Stream[@streamType=1]/@bitDepth'", "ReqLevel" : 2, "id" : 72},
				"Video Stream Duration" : {"field" : "Media/Part/Stream[@streamType=1]/@duration", "ReqLevel" : 2, "id" : 73},
				"Video Stream Level" : {"field" : "Media/Part/Stream[@streamType=1]/@level", "ReqLevel" : 2, "id" : 74},
				"Audio Stream Selected" : {"field" : "Media/Part/Stream[@streamType=2]/@selected", "ReqLevel" : 2, "id" : 75},
				"Audio Stream Default" : {"field" : "Media/Part/Stream[@streamType=2]/@default", "ReqLevel" : 2, "id" : 76},
				"Audio Stream Codec" : {"field" : "Media/Part/Stream[@streamType=2]/@codec", "ReqLevel" : 2, "id" : 77},
				"Audio Stream Index" : {"field" : "Media/Part/Stream[@streamType=2]/@index", "ReqLevel" : 2, "id" : 78},
				"Audio Stream Channels" : {"field" : "Media/Part/Stream[@streamType=2]/@channels", "ReqLevel" : 2, "id" : 79},
				"Audio Stream Bitrate" : {"field" : "Media/Part/Stream[@streamType=2]/@bitrate", "ReqLevel" : 2, "id" : 80},
				"Audio Stream Language" : {"field" : "Media/Part/Stream[@streamType=2]/@language", "ReqLevel" : 2, "id" : 81},
				"Audio Stream Language Code" : {"field" : "Media/Part/Stream[@streamType=2]/@languageCode", "ReqLevel" : 2, "id" : 82},
				"Audio Stream Audio Channel Layout" : {"field" : "Media/Part/Stream[@streamType=2]/@audioChannelLayout", "ReqLevel" : 2, "id" : 83},
				"Audio Stream Bit Depth" : {"field" : "Media/Part/Stream[@streamType=2]/@bitDepth", "ReqLevel" : 2, "id" : 84},
				"Audio Stream Bitrate Mode" : {"field" : "Media/Part/Stream[@streamType=2]/@bitrateMode", "ReqLevel" : 2, "id" : 85},
				"Audio Stream Codec ID" : {"field" : "Media/Part/Stream[@streamType=2]/@codecID", "ReqLevel" : 2, "id" : 86},
				"Audio Stream Duration" : {"field" : "Media/Part/Stream[@streamType=2]/@duration", "ReqLevel" : 2, "id" : 87},
				"Audio Stream Profile" : {"field" : "Media/Part/Stream[@streamType=2]/@profile", "ReqLevel" : 2, "id" : 88},
				"Audio Stream Sampling Rate" : {"field" : "Media/Part/Stream[@streamType=2]/@samplingRate", "ReqLevel" : 2, "id" : 89},
				"Subtitle Stream Codec" : {"field" : "Media/Part/Stream[@streamType=3]/@codec", "ReqLevel" : 2, "id" : 90},
				"Subtitle Stream Index" : {"field" : "Media/Part/Stream[@streamType=3]/@index", "ReqLevel" : 2, "id" : 91},
				"Subtitle Stream Language" : {"field" : "Media/Part/Stream[@streamType=3]/@language", "ReqLevel" : 2, "id" : 92},
				"Subtitle Stream Language Code" : {"field" : "Media/Part/Stream[@streamType=3]/@languageCode", "ReqLevel" : 2, "id" : 93},
				"Subtitle Stream Codec ID" : {"field" : "Media/Part/Stream[@streamType=3]/@codecID", "ReqLevel" : 2, "id" : 94},
				"Subtitle Stream Format" : {"field" : "Media/Part/Stream[@streamType=3]/@format", "ReqLevel" : 2, "id" : 95},
				"Subtitle Stream Title" : {"field" : "Media/Part/Stream[@streamType=3]/@title", "ReqLevel" : 2, "id" : 96},
				"Subtitle Stream Selected" : {"field" : "Media/Part/Stream[@streamType=3]/@selected", "ReqLevel" : 2, "id" : 97}
}

levels = {
				"Level_1" : ['Media ID', 'Title', 'Sort title', 'Studio', 'Content Rating',
									'Year', 'Rating', 'Summary', 'Genres'],
				"Level_2" : ['View Count', 'Last Viewed at', 'Tagline', 'Release Date',
									'Writers', 'Country', 'Duration', 'Directors', 'Roles', 'IMDB Id'],
				"Level_3" : ['Labels', 'Locked Fields', 'Extras', 'Collections', 'Original Title',
									'Added', 'Updated', 'Audio Languages', 'Audio Title', 'Subtitle Languages',
									'Subtitle Title', 'Subtitle Codec', 'Accessible', 'Exists'],
				"Level_4" : ['Video Resolution', 'Bitrate', 'Width', 'Height', 'Aspect Ratio',
									'Audio Channels', 'Audio Codec', 'Video Codec', 'Container', 'Video FrameRate'],
				"Level_5" : ['Part File', 'Part Size', 'Part Indexed', 'Part Duration', 'Part Container',
									'Part Optimized for Streaming'],
				"Level_6" : ['Video Stream Title', 'Video Stream Default', 'Video Stream Index','Video Stream Pixel Format',
									'Video Stream Profile', 'Video Stream Ref Frames', 'Video Stream Scan Type', 
									'Video Stream Stream Identifier',	'Video Stream Width', 'Video Stream Pixel Aspect Ratio',
									'Video Stream Height', 'Video Stream Has Scaling Matrix', 'Video Stream Frame Rate Mode',
									'Video Stream Frame Rate', 'Video Stream Codec', 'Video Stream Codec ID',
									'Video Stream Chroma Sub Sampling', 'Video Stream Cabac', 'Video Stream Anamorphic',
									'Video Stream Language Code', 'Video Stream Language', 'Video Stream Bitrate',
									'Video Stream Bit Depth', 'Video Stream Duration', 'Video Stream Level',
									'Audio Stream Selected', 'Audio Stream Default', 'Audio Stream Codec',
									'Audio Stream Index', 'Audio Stream Channels', 'Audio Stream Bitrate', 'Audio Stream Language',
									'Audio Stream Language Code', 'Audio Stream Audio Channel Layout', 'Audio Stream Bit Depth',
									'Audio Stream Bitrate Mode', 'Audio Stream Codec ID', 'Audio Stream Duration',
									'Audio Stream Profile', 'Audio Stream Sampling Rate', 'Subtitle Stream Codec',
									'Subtitle Stream Index', 'Subtitle Stream Language', 'Subtitle Stream Language Code',
									'Subtitle Stream Codec ID', 'Subtitle Stream Format', 'Subtitle Stream Title', 'Subtitle Stream Selected']
}
